inoremap == <Space>==<Space>
inoremap === <Space>===<Space>
"inoremap = <Space>=<Space>
inoremap != <Space>!=<Space>
inoremap += <Space>+=<Space>
inoremap -= <Space>-=<Space>
inoremap *= <Space>*=<Space>
inoremap /= <Space>/=<Space>
inoremap .= <Space>.=<Space>
inoremap , ,<Space>
